// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3QmHDohm4L99crCxZ71sFrpBXfF_PgE',
    appId: '1:903860874588:web:6d65696b70924c834fe599',
    messagingSenderId: '903860874588',
    projectId: 'pregnancy-support-system',
    authDomain: 'pregnancy-support-system.firebaseapp.com',
    storageBucket: 'pregnancy-support-system.firebasestorage.app',
    measurementId: 'G-NZVQW005QY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7I-aHD2n7gb0fINN_3AU8CqvDo4uYyps',
    appId: '1:903860874588:android:c8431244903e83394fe599',
    messagingSenderId: '903860874588',
    projectId: 'pregnancy-support-system',
    storageBucket: 'pregnancy-support-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxp3nS8QBlFLxoc4ysccjeJG_m5-LJOjQ',
    appId: '1:903860874588:ios:77c431ff2b0350c44fe599',
    messagingSenderId: '903860874588',
    projectId: 'pregnancy-support-system',
    storageBucket: 'pregnancy-support-system.firebasestorage.app',
    androidClientId: '903860874588-hhu7g5vh4fp3ucbpjoe7m3fltbjltu7l.apps.googleusercontent.com',
    iosClientId: '903860874588-346q8tm6pe7160igm9tq2elfjo9humk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pregnancySupport',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxp3nS8QBlFLxoc4ysccjeJG_m5-LJOjQ',
    appId: '1:903860874588:ios:77c431ff2b0350c44fe599',
    messagingSenderId: '903860874588',
    projectId: 'pregnancy-support-system',
    storageBucket: 'pregnancy-support-system.firebasestorage.app',
    androidClientId: '903860874588-hhu7g5vh4fp3ucbpjoe7m3fltbjltu7l.apps.googleusercontent.com',
    iosClientId: '903860874588-346q8tm6pe7160igm9tq2elfjo9humk3.apps.googleusercontent.com',
    iosBundleId: 'com.example.pregnancySupport',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF3QmHDohm4L99crCxZ71sFrpBXfF_PgE',
    appId: '1:903860874588:web:e98105d89e521f4f4fe599',
    messagingSenderId: '903860874588',
    projectId: 'pregnancy-support-system',
    authDomain: 'pregnancy-support-system.firebaseapp.com',
    storageBucket: 'pregnancy-support-system.firebasestorage.app',
    measurementId: 'G-WJ7HPYGEN4',
  );

}